server:
  port: 8080

spring:
  application:
    name: image-upload-service
  
  # datasource:
  #   url: jdbc:mysql://47.108.76.91:3306/pixel_dock?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  #   username: root
  #   password: root
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.MySQL8Dialect
  #       format_sql: true

minio:
  endpoint: http://47.108.76.91:9000
  accessKey: admin
  secretKey: admin123
  bucket: pic
  region: us-east-1

logging:
  level:
    com.pixeldock: DEBUG
    org.springframework.web: DEBUG
